#!/bin/bash

SECURE_CONNECTIONS=("vpn" "tun" "tap" "wireguard" "openvpn" "openconnect" "wireguard-vpn")
ICON=""

# Find first secure connection
CONNECTION=""
while IFS=: read -r NAME TYPE; do
    for SECURE in "${SECURE_CONNECTIONS[@]}"; do
        if [[ "$TYPE" == "$SECURE" ]]; then 
          CONNECTION=$NAME 
          break 2
        fi
    done
done < <(LC_ALL=C.utf8 nmcli -t -f NAME,TYPE connection show --active)

# OUTPUT
LABEL_COLOR=${vpn_label_color:-$(xrescat i3xrocks.label.color)}
VALUE_COLOR="${vpn_color:-$(xrescat i3xrocks.value.color)}"
VALUE_FONT=${font:-$(xrescat i3xrocks.value.font)}

if [[ -n "$CONNECTION" ]]; then
    echo "<span color=\"${LABEL_COLOR}\" font_desc=\"${VALUE_FONT}\">${ICON} </span><span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\">$CONNECTION</span>" # full text
    echo "<span color=\"${LABEL_COLOR}\" font_desc=\"${VALUE_FONT}\">${ICON} </span>" # short text
fi
